#!/usr/bin/env python3

# bulldozer
import os
import argparse
import shutil
from pathlib import Path
from classes.dupe_checker import DupeChecker
from classes.podcast import Podcast
from classes.torrent_creator import TorrentCreator
from classes.utils import load_config, setup_logging, announce, ask_yes_no, check_config, log, fix_folder_name
from classes.utils import rename_folder
from classes.report import Report

config = load_config()

def main(input, censor_rss, report_only=False, search_term=None, download_only=False, refresh=False, name=None, match_titles=None, after_date=None, before_date=None, threads=None, latest_episode_only=False):
    """
    Main function to run the bulldozer script

    :param input: The input to the script, can be a directory path, RSS feed URL, or local RSS file path
    :param censor_rss: Whether to censor the RSS feed or not
    """
    global config
    print("· • —– ++ ---| Bulldozer v0.7.4 |--- ++ —– • ·")
    database_active = config.get("database", {}).get("active", True)

    if os.path.isdir(input):
        folder_path = Path(input)
        if not name:
            name = folder_path.name
        check_duplicates = not report_only
        podcast = Podcast(name, folder_path, config, censor_rss=censor_rss, check_duplicates=check_duplicates, search_term=search_term)
        new_name = fix_folder_name(name)
        if new_name != name and ask_yes_no(f"Would you like to rename the folder to {new_name}"):
            rename_folder(podcast, new_name)
            podcast.name = name = new_name
            podcast.rss.rename()
    else:
        source_rss_file = input
        output_dir = config.get("output_dir", ".")
        if not name:
            name = "unknown podcast"
            temp_dir = Path(output_dir) / 'download_temp'
        else:
            temp_dir = Path(output_dir) / f"{name}"
        if temp_dir.exists():
            if ask_yes_no(f"The directory where the podcast will be downloaded already exists. Would you like to delete it?"):
                shutil.rmtree(temp_dir)
            else:
                announce(f"Exiting. Please check {temp_dir} and remove it to continue.", "info")
                return
        temp_dir.mkdir(parents=True, exist_ok=True)
        podcast = Podcast(name, temp_dir, config, source_rss_file, censor_rss, True, search_term, match_titles, after_date, before_date, latest_episode_only)
        podcast.download_episodes(threads)
        name = podcast.name
        folder_path = temp_dir

    if download_only:
        announce(f"Podcast downloaded!", "celebrate")
        return
    if database_active:
        podcast.load_from_database(refresh)

    podcast.analyze_files()

    if database_active and not podcast.analyzer.original_files:
        podcast.add_to_database(refresh)

    if not report_only:
        podcast.organize_files()
        
    report  = Report(podcast, config)
    report_exists = report.check_if_report_exists()
    generate_report = True
    if report_exists:
        report_filename = report.get_file_path()
        if not ask_yes_no(f"Report {report_filename} already exists. Overwrite?"):
            log(f"Report {report_filename} already exists. Skipping report generation.", "debug")
            generate_report = False
        else:
            log(f"Overwriting report {report_filename}", "debug")

    if not podcast.metadata.has_data and generate_report:
        podcast.metadata.load(search_term)
    if not podcast.metadata.has_data and generate_report:
        announce(f"Failed to load metadata for {name}, skipping report generation", "warning")
    elif generate_report:
        if database_active:
            podcast.add_metadata_to_database()
        report.generate()
    if report_only:
        podcast.db.close()
        return
    podcast.archive_files()

    announce_url = config.get("announce_url", None)
    base_dir = config.get("base_dir", None)
    tracker_source = config.get("tracker_source", None)
    create_torrent(podcast, announce_url, base_dir, tracker_source)
    podcast.db.close()
    move_folder = config.get("move", {}).get("active", False)
    move_folder_path = config.get("move", {}).get("path", None)
    if move_folder and move_folder_path:
        ask_to_move = config.get("move", {}).get("ask", True)
        if ask_to_move and ask_yes_no(f"Would you like to move the folder to {move_folder_path}"):
            move_folder_path = Path(move_folder_path)
            if move_folder_path.exists() and move_folder_path.is_dir():
                new_folder_path = move_folder_path / podcast.folder_path.name
                if new_folder_path.exists():
                    announce(f"Folder {new_folder_path} already exists, skipping move", "warning")
                else:
                    shutil.move(str(podcast.folder_path), str(new_folder_path))
                    announce(f"Moved folder to {new_folder_path}", "info")
            else:
                announce(f"Move folder {move_folder_path} does not exist", "error")
    announce(f"All done, enjoy!", "celebrate")

def check_files(input):
    """
    Check the files in the given folder

    :param input: The folder path to check
    """
    global config
    folder_path = Path(input)
    if folder_path.exists() and folder_path.is_dir():
        name = folder_path.name
        podcast = Podcast(name, folder_path, config, check_duplicates=False)
        podcast.analyze_files()
        report = Report(podcast, config)
        report.generate(True)
    else:
        announce(f"Folder {folder_path} does not exist", "critical")

def create_torrent(podcast, announce_url, base_dir, tracker_source):
    """
    Create a torrent file for the given podcast

    :param podcast: The podcast object to create the torrent for
    :param announce_url: The announce URL to use for the torrent
    :param base_dir: The base directory to use for the torrent
    :param tracker_source: The source to use for the tracker
    """
    if not announce_url:
        announce(f"Skipping torrent creation for {podcast.name}, no announce URL provided", "info")
        return
    torrent_creator = TorrentCreator(podcast, announce_url, base_dir, tracker_source)
    total_size = sum(f.stat().st_size for f in podcast.folder_path.rglob('*') if f.is_file())
    piece_size = torrent_creator.calculate_piece_size(total_size)
    if ask_yes_no(f'Would you like to create the torrent now (piece size calcualted to {piece_size})'):
        torrent_creator.create_torrent(piece_size)

def make_torrent(input):
    """
    Make a torrent file for the given folder

    :param input: The folder path to create the torrent for
    """
    global config
    folder_path = Path(input)
    if folder_path.exists() and folder_path.is_dir():
        name = folder_path.name
        podcast = Podcast(name, folder_path, config, check_duplicates=False)
        announce_url = config.get("announce_url")
        base_dir = config.get("base_dir", None)
        tracker_source = config.get("tracker_source", None)
        create_torrent(podcast, announce_url, base_dir, tracker_source)
    else:
        announce(f"Folder {folder_path} does not exist", "error")
        return
    announce(f"All done, enjoy!", "celebrate")

def dupecheck(input):
    """
    Perform a dupecheck on the given input

    :param input: The name to dupecheck
    """
    dupecheck = config.get("dupecheck", False)
    if not dupecheck:
        announce("Dupecheck is not enabled in the config", "info")
        return
    api_key = config.get("api_key")
    dupecheck_url = config.get("dupecheck_url")
    
    dupe_checker = DupeChecker(input, dupecheck_url, api_key, False)
    dupe_checker.check_duplicates(True)

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Podcast Automator Script")
    parser.add_argument("input", nargs="?", help="RSS feed URL, directory path, local RSS file path, or name to dupecheck")
    parser.add_argument("--censor-rss", action="store_true", help="Make sure the RSS feed is censored")
    parser.add_argument("--report-only", action="store_true", help="Generates a report only")
    parser.add_argument("--download-only", action="store_true", help="Only download the files")
    parser.add_argument("--refresh", action="store_true", help="Don't read data from the database")
    parser.add_argument("--check-files", action="store_true", help="Only check the files")
    parser.add_argument("--dupecheck", action="store_true", help="Perform a dupecheck")
    parser.add_argument("--make-torrent", action="store_true", help="Only make a torrent file")
    parser.add_argument("--check-config", action="store_true", help="Check that user config is valid")
    parser.add_argument("--log-level", type=str, help="Set the logging level (e.g., DEBUG, INFO, WARNING, ERROR, CRITICAL)")
    parser.add_argument("--search-term", type=str, help="Search term to use when querying APIs")
    parser.add_argument("--name", type=str, help="Override the name to use for the podcast")
    parser.add_argument("--match-titles", type=str, help="Only includes the episodes with titles matching the given string")
    parser.add_argument("--after", type=str, help="Only include episodes published after this date (YYYY-MM-DD format)")
    parser.add_argument("--before", type=str, help="Only include episodes published before this date (YYYY-MM-DD format)")
    parser.add_argument("--threads", type=int, help="Number of threads to use for podcast-dl downloading (overrides config setting)")
    parser.add_argument("--latest-episode-only", action="store_true", help="Only download the latest episode")
    args = parser.parse_args()

    if not config:
        exit(1)

    setup_logging(args.log_level, config)

    if not args.check_config and not args.input:
        parser.error("the 'input' argument is required unless '--check-config' is specified")

    if args.make_torrent:
        make_torrent(args.input)
    elif args.dupecheck:
        dupecheck(args.input)
    elif args.check_files:
        check_files(args.input)
    elif args.check_config:
        check_config()
    else:
        main(args.input, args.censor_rss, args.report_only, args.search_term, args.download_only, args.refresh, args.name, args.match_titles, args.after, args.before, args.threads, args.latest_episode_only)
